server:
  port: 8082

spring:
  application:
    name: activity-service # Using dash-case is standard for Eureka registration IDs

  main:
    allow-bean-definition-overriding: true

  cloud:
    compatibility-verifier:
      enabled: false # Bypasses the Spring Boot 3.5.0 version check failure

  data:
    mongodb:
      uri: mongodb://localhost:27017/fitnessactivity
  radditmq:
    host: localhost
    post: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

rabbitmq:
  exchange:
    name: fitness.exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking