server:
  port: 8084

spring:
  application:
    name: user-service
  main:
    allow-bean-definition-overriding: true
  cloud:
    compatibility-verifier:
      enabled: false

  datasource:
    url: jdbc:postgresql://localhost:5432/fitness_user_db
    username: postgres
    password: '6056'

  jpa:
    open-in-view: false  # Disables the warning log you had earlier
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/