server:
  port: 8081

spring:
  application:
    name: user-service

  main:
    allow-bean-definition-overriding: true

  cloud:
    compatibility-verifier:
      enabled: false

  datasource:
    url: jdbc:postgresql://localhost:5432/fitness_user_db
    username: postgres
    password: '6056'

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/